insert Platnosci (platnosc) values('gotówka')
insert Platnosci (platnosc) values('Aareal Bank')
insert Platnosci (platnosc) values('Alior Bank')
insert Platnosci (platnosc) values('Bank BPH')
insert Platnosci (platnosc) values('Bank DnB NORD Polska')
insert Platnosci (platnosc) values('Bank Gospodarki ¯ywnoœciowej')
insert Platnosci (platnosc) values('Bank Gospodarstwa Krajowego')
insert Platnosci (platnosc) values('Bank Handlowy')
insert Platnosci (platnosc) values('Bank Millennium')
insert Platnosci (platnosc) values('Bank Ochrony Œrodowiska')
insert Platnosci (platnosc) values('Bank of Tokyo-Mitsubishi UFJ Polska')
insert Platnosci (platnosc) values('Bank Pekao')
insert Platnosci (platnosc) values('Bank Pocztowy')
insert Platnosci (platnosc) values('Bank Zachodni WBK')
insert Platnosci (platnosc) values('Banque PSA Finance')
insert Platnosci (platnosc) values('BNP Paribas Bank Polska')
insert Platnosci (platnosc) values('MBank')
insert Platnosci (platnosc) values('Millenium Bank')
insert Platnosci (platnosc) values('BRE Bank Hipoteczny')
insert Platnosci (platnosc) values('Calyon Bank Polska')
insert Platnosci (platnosc) values('Credit Agricole Bank Polska')
insert Platnosci (platnosc) values('DaimlerChrysler Bank Polska')
insert Platnosci (platnosc) values('Danske Bank Polska')
insert Platnosci (platnosc) values('Deutsche Bank PBC')
insert Platnosci (platnosc) values('Deutsche Bank Polska')
insert Platnosci (platnosc) values('Dresdner Bank Polska')
insert Platnosci (platnosc) values('DZ Bank Polska')
insert Platnosci (platnosc) values('Euro Bank')
insert Platnosci (platnosc) values('FCE Bank Polska')
insert Platnosci (platnosc) values('Fiat Bank Polska')
insert Platnosci (platnosc) values('FM Bank Polska')
insert Platnosci (platnosc) values('Getin Noble Bank')
insert Platnosci (platnosc) values('HSBC Bank Polska')
insert Platnosci (platnosc) values('ING Bank Œl¹ski')
insert Platnosci (platnosc) values('Invest Bank')
insert Platnosci (platnosc) values('Jyske Bank A/S SA')
insert Platnosci (platnosc) values('Kredyt Bank')
insert Platnosci (platnosc) values('Meritum Bank ICB')
insert Platnosci (platnosc) values('Nordea Bank Polska')
insert Platnosci (platnosc) values('Nykredit Realkredit A/S')
insert Platnosci (platnosc) values('Pekao Bank Hipoteczny')
insert Platnosci (platnosc) values('Powszechna Kasa Oszczêdnoœci Bank Polski SA')
insert Platnosci (platnosc) values('Polski Bank Przedsiêbiorczoœci S.A.')
insert Platnosci (platnosc) values('Rabobank Polska')
insert Platnosci (platnosc) values('Raiffeisen Polbank')
insert Platnosci (platnosc) values('RBS Bank')
insert Platnosci (platnosc) values('RCI Bank Polska')
insert Platnosci (platnosc) values('Santander Consumer Bank')
insert Platnosci (platnosc) values('Spó³dzielczy Bank Rozwoju')
insert Platnosci (platnosc) values('Société Générale')
insert Platnosci (platnosc) values('Svenska Handelsbanken')
insert Platnosci (platnosc) values('Sygma Banque')
insert Platnosci (platnosc) values('Œl¹ski Bank Hipoteczny')
insert Platnosci (platnosc) values('Toyota Bank Polska')
insert Platnosci (platnosc) values('Volkswagen Bank Polska')
